### ISSUE TITLE
mvn command fails 

### ISSUE THREAD

**Issue by salvob41** [smallnest/kafka-example-in-scala#1]
When running che command 
`mvn clean package`
it fails:

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project kafka_example: Compilation failure: Compilation failure:
[ERROR] /tmp/example/kafka-example-in-scala/src/main/java/com/colobu/kafka/ConsumerExample.java:[52,5] error: generics are not supported in -source 1.3
[ERROR]
[ERROR](use -source 5 or higher to enable generics)
[ERROR] /tmp/example/kafka-example-in-scala/src/main/java/com/colobu/kafka/ConsumerExample.java:[60,48] error: enhanced for loops are not supported in -source 1.3
[ERROR]
[ERROR](use -source 5 or higher to enable for-each loops)
[ERROR] /tmp/example/kafka-example-in-scala/src/main/java/com/colobu/kafka/ProducerExample.java:[32,16] error: generics are not supported in -source 1.3
[ERROR]
[ERROR](use -source 5 or higher to enable generics)
[ERROR] /tmp/example/kafka-example-in-scala/src/main/java/com/colobu/kafka/ConsumerTest.java:[14,20] error: generics are not supported in -source 1.3
[ERROR] -> [Help 1]
[ERROR]

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

`

**Comment by smallnest** [comment]
your JDK version is too old.
You should upgrade your JDK to 1.7 or 1.8

**Comment by salvob41** [comment]
Thanks for the reply.

My JDK version is update to 1.7, for some reason `mvn` choose by default a 1.3 version of the JDK.
I figured that there was a problem in the compiler, since I've never used the `maven-shade-plugin` I added the following plugin, specifying the JDK version (1.7):
`
<plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-compiler-plugin</artifactId>
       <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
       </configuration>
 </plugin>
`

That worked out fine with me.

**Comment by smallnest** [comment]
yes. Another solution is adding the below properties:

``` xml
<properties>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
</properties>
```
