### ISSUE TITLE
Why and where do you use the Delay?

### ISSUE THREAD

**Issue by vishnu667** [smallnest/kafka-example-in-scala#4]
Hey I was going through your implementation. 
And I see that you pass a variable Delay in the Scala Consumer. 
It is not being used anywhere in the code?

https://github.com/smallnest/kafka-example-in-scala/blob/master/src/main/scala/com/colobu/kafka/ScalaConsumerExample.scala#L59

**Comment by smallnest** [comment]
see java code:

https://github.com/smallnest/kafka-example-in-scala/blob/master/src/main/java/com/colobu/kafka/ConsumerTest.java#L33

I want to add thread sleep to test. I will add it later

**Comment by smallnest** [comment]
refactored. And add examples for kafka 0.9.0.1 and kafka 0.10.1.0
